language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.8"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb herbstluftwm
install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda env create --file environment.yml --name testenv
  - conda activate testenv
  - pip install -ve . --no-deps

  # Dump environment to console for easy debugging
  - conda env export

before_script:
  - "herbstluftwm &"
  - sleep 1
script:
- python -m unittest -v
